/**
 * Asset manifest - AUTO-GENERATED by build-manifest.mjs
 * DO NOT EDIT MANUALLY
 */

export interface AssetManifest {
  models: string[];
  textures: string[];
  audio: string[];
  ui: string[];
  data: string[];
}

export const assetManifest: AssetManifest = {
  "models": [],
  "textures": [],
  "audio": [],
  "ui": [],
  "data": []
};
